### PR TITLE
Adds font-size picker to settings menu

### PR DESCRIPTION
**Pull request by hubwoop**
Font size is set via a placeholder in the base theme

### CODE REVIEW

**Comment by tbolender** [comment]
Great idea! I will have a closer look later today

**Comment by tbolender** [comment]
Looks good, would merge it. Just one thing to be sure: You only care about the font size when reading post in full, right?

**Comment by hubwoop** [comment]
Cool 😎!

Yes, that was my intent. A general font setting could be nice right? But for now this is what I need most to be able to read the posts.

BTW thanks for this nice app :)!

**Comment by tbolender** [comment]
Welcome! I am always happy to see further improvements. I just wanted to make sure that it was your intention not to change the font size in the overview list.

**Pull request merged**
